### ISSUE TITLE
공지사항 보기에서 에러남 

### ISSUE THREAD

**Issue by capacitate** [weumj/TheUOS#1]
재연 방법: 앱 열고 - 공지사항 - 공지사항 선택 변경
에러! : length = 1; index = 1
이게 팝업으로 나오는데, 귀찮겠지만.. 확인해줄 수 있나? 
![kakaotalk_photo_2017-03-03-07-14-15](https://cloud.githubusercontent.com/assets/12195203/23529461/13f73154-ffe1-11e6-8d5e-0762400d1c30.jpeg)

**Comment by weumj** [comment]
주말 안으로 확인해볼께

**Comment by weumj** [comment]
지원 중단한 버전 (`com.uoscs09.theuos`) 이슈
